import { GoogleGenAI } from "@google/genai";
import ApiError from "../utils/ApiError.js";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY! });

const PROMPT = `TASK: Convert the input 2D floor plan into a photorealistic, top-down 3D architectural render.

REQUIREMENTS:
- Maintain the exact same layout and proportions as the input floor plan
- Add photorealistic materials: hardwood floors, tiles, carpet as appropriate
- Include realistic furniture placement and interior design elements
- Apply professional architectural lighting with natural light from windows
- Render from a top-down perspective showing the complete floor plan
- Add realistic shadows, textures, and depth
- Make it look like a professional architectural visualization

OUTPUT: A single photorealistic top-down 3D architectural render of the floor plan.`;

export const generateRender = async (
    buffer: Buffer,
    mimeType: string
): Promise<{ imageBuffer: Buffer; mimeType: string }> => {
    try {
        const base64Image = buffer.toString("base64");

        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash-image",
            contents: [
                {
                    role: "user",
                    parts: [
                        {
                            inlineData: {
                                mimeType,
                                data: base64Image,
                            }
                        },
                        {
                            text: PROMPT
                        }
                    ]
                }
            ],
            config: {
                responseModalities: ["TEXT", "IMAGE"],
            }
        });

        const candidates = response.candidates;
        if (!candidates || candidates.length === 0) {
            throw new ApiError(500, "No response from Gemini");
        }

        const candidate = candidates[0];
        if (!candidate.content || !candidate.content.parts) {
            throw new ApiError(500, "Empty response from Gemini");
        }

        for (const part of candidate.content.parts) {
            if (part.inlineData) {
                const imageBuffer = Buffer.from(part.inlineData.data!, "base64");
                return {
                    imageBuffer,
                    mimeType: part.inlineData.mimeType!,
                };
            }
        }

        throw new ApiError(500, "No image generated by Gemini");

    } catch (error: any) {
        if (error instanceof ApiError) throw error;
        throw new ApiError(500, `Gemini API error: ${error.message}`);
    }
};